{% set base_name = "libignition-math" %}
{% set version = "6.10.0" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-math/archive/ignition-math{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: 9e00284cd6d51afe190165b2b44258e19bd4a28781cbacf21fd6b0bae43c16aa
    patches:
      - disable_fake_install.patch  # ["linux-aarch64" == target_platform]
      - 384.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make                               # [not win]
    - cmake
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - pybind11-abi                           # [build_platform != target_platform]
  host:
    - libignition-cmake2
    - eigen
    - python
    - pybind11
    - pybind11-abi
  run:
    - libignition-cmake2
    - eigen
    - python

test:
  commands:
    - test -f ${PREFIX}/include/ignition/math6/ignition/math.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-math6.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-math6.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-math6/ignition-math6-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\math6\\ignition\\math.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-math6.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-math6.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-math6\\ignition-math6-config.cmake (exit 0) else (exit 1)  # [win]
  imports:
    - ignition.math

about:
  home: https://github.com/ignitionrobotics/ign-math
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition Math : Math classes and functions for robot applications'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
