{% set base_name = "libignition-math" %}
{% set version = "6.6.0" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-math/archive/ignition-math{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: 8fd06206e7e3d28a9c8ff54f7c9eaa3f01178170bd31ad57c6bc672ecb0c3645
    patches:
      - cctype_include.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - make                               # [not win]
    - cmake
  host:
    - libignition-cmake2
    - eigen
  run:
    - libignition-cmake2
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/ignition/math6/ignition/math.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-math6.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-math6.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-math6/ignition-math6-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\math6\\ignition\\math.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-math6.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-math6.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-math6\\ignition-math6-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/ignitionrobotics/ign-math
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition Math : Math classes and functions for robot applications'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
