{% set base_name = "libignition-math" %}
{% set version = "6.8.0" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-math/archive/ignition-math{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: 07c4fa9eeaa51fe2b4ee2855ea69bb16571d7e6c315b8b0726fc4383b64303a1

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make                               # [not win]
    - cmake
  host:
    - libignition-cmake2
    - eigen
  run:
    - libignition-cmake2
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/ignition/math6/ignition/math.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-math6.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-math6.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-math6/ignition-math6-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\math6\\ignition\\math.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-math6.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-math6.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-math6\\ignition-math6-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-math
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition Math : Math classes and functions for robot applications'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
